export default new Map([
	[
		'lead1',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'lead2',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'lead3',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'avr',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'avl',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'avf',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v1',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v2',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v3',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v4',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v5',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'v6',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
	[
		'global',
		[
			{
				feature: 'pwave',
				characteristic: 'amplitude',
				min: 1,
				max: 15,
				value: 2,
				increment: 0.1,
			},
			{
				feature: 'pwave',
				characteristic: 'width',
				min: 1,
				max: 10,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'printerval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'amplitude',
				min: -10,
				max: 15,
				value: 10,
				increment: 0.1,
			},
			{
				feature: 'qrswave',
				characteristic: 'width',
				min: 2,
				max: 5,
				value: 3,
				increment: 0.1,
			},
			{
				feature: 'stinterval',
				characteristic: 'width',
				min: 1,
				max: 13,
				value: 1,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'amplitude',
				min: -3,
				max: 10,
				value: 5,
				increment: 0.1,
			},
			{
				feature: 'twave',
				characteristic: 'width',
				min: 5,
				max: 10,
				value: 5,
				increment: 0.1,
			},
		],
	],
])
