export default [
	{
		feature: 'pwave',
		characteristic: 'amplitude',
		min: 1,
		max: 15,
		value: 2,
		increment: 0.1,
	},
	{
		feature: 'pwave',
		characteristic: 'width',
		min: 1,
		max: 10,
		value: 3,
		increment: 0.1,
	},
	{
		feature: 'printerval',
		characteristic: 'width',
		min: 1,
		max: 13,
		value: 1,
		increment: 0.1,
	},
	{
		feature: 'qrswave',
		characteristic: 'amplitude',
		min: -10,
		max: 15,
		value: 10,
		increment: 0.1,
	},
	{
		feature: 'qrswave',
		characteristic: 'width',
		min: 2,
		max: 5,
		value: 3,
		increment: 0.1,
	},
	{
		feature: 'stinterval',
		characteristic: 'width',
		min: 1,
		max: 13,
		value: 1,
		increment: 0.1,
	},
	{
		feature: 'twave',
		characteristic: 'amplitude',
		min: -3,
		max: 10,
		value: 5,
		increment: 0.1,
	},
	{
		feature: 'twave',
		characteristic: 'width',
		min: 5,
		max: 10,
		value: 5,
		increment: 0.1,
	},
]
